---
- name: Demo Ruleset for Webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Chay job lay thon tin Datacenter trong Vcenter
      condition: event.payload.message == "Hello EDA"
      action:
        run_job_template:
          name: get-info-datacenter-vlware # Ten cua template tren AWX server
          organization: Default